### PR TITLE
Node engine update

### PR DESCRIPTION
**Pull request by chriswhittaker**
- Updates the node engine version so that the plugin can be used with versions beyond 18.20.2

### CODE REVIEW

**Comment by wkentdag** [comment]
thanks for the PR! I won't have time to look into the failing tests til later this week, but will get this merged once they're passing.

**Comment by chriswhittaker** [comment]
@wkentdag No worries, thank you!

**Comment by chriswhittaker** [comment]
@wkentdag Hey there! Any chance you were able to look into the failing tests? The feature seems to work fine when I run locally with the node upgrade changes. 

I could not get the tests to pass when running them locally against `main`, even without the node version changes

**Comment by wkentdag** [comment]
@chriswhittaker My guess is that something is misconfigured with the GH actions test runner. I'm sure it works locally but I'm not going to merge a PR with failing tests. If you feel like investigating, please go ahead and push some more changes here, if the tests pass I'll merge. Otherwise it'll have to just wait until I have some more free time - sorry!

**Comment by wkentdag** [comment]
@chriswhittaker this update is available in v0.0.6. thanks again for the contribution and apologies for the long delay!

**Pull request closed without merging**
